### ISSUE TITLE
Figure out styling issues w/ `<table>` elements in `table.html` 

### ISSUE THREAD

**Issue by vtlanglois** [vtlanglois/GWD#5]

**Comment by takidilmi** [comment]
i know am new in this, but wouldn't adding "style" make it even better?
can try that if you allow me though, and yah can change the img position + the text lining in "snippets-demo.html"

**Comment by vtlanglois** [comment]
Hey @takidilmi 

Thank you for your input, but I won't need help with this issue.

**Comment by vtlanglois** [comment]
`tables.html` now uses `:where()` to select HTML elements
